wandb_version: 1

wandb:
  desc: null
  value: true
name:
  desc: null
  value: lstm-enc-dec-0.0001-2-12-9279410np
num_features:
  desc: null
  value: 30
hidden_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0
input_window:
  desc: null
  value: 2
output_window:
  desc: null
  value: 12
learning_rate:
  desc: null
  value: 0.0001
num_layers:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 250
batch_size:
  desc: null
  value: 128
train_data_len:
  desc: null
  value: 200000
training_prediction:
  desc: null
  value: recursive
loss_type:
  desc: null
  value: MSE
model_label:
  desc: null
  value: ENC-DEC-100k-DATA
teacher_forcing_ratio:
  desc: null
  value: 0.6
dynamic_tf:
  desc: null
  value: true
shuffle:
  desc: null
  value: true
one_hot_month:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692445934.022071
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 1
      - 2
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.15.8
      8:
      - 5
